// <auto-generated />
using System;
using BuildingBlocks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildingBlocks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260417095819_AddGroupTreeAndDevicesFoundation")]
    partial class AddGroupTreeAndDevicesFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthLastActiveDeviceAccount", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsOfflineRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offline_restricted");

                    b.Property<DateTimeOffset>("MarkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId")
                        .HasName("pk_auth_last_active_device_accounts");

                    b.HasIndex("UserId");

                    b.ToTable("auth_last_active_device_accounts", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auth_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_permissions_code");

                    b.ToTable("auth_permissions", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("402957af-25c0-455b-a753-1576a5ecfa91"),
                            Code = "auth.session.sign_in",
                            Name = "Auth Session Sign In"
                        },
                        new
                        {
                            Id = new Guid("6a6f1e27-b895-423a-af08-f0a1d8e77b0d"),
                            Code = "auth.session.refresh",
                            Name = "Auth Session Refresh"
                        },
                        new
                        {
                            Id = new Guid("34d52b4e-d652-4d27-9f4a-6d6f706ce3c0"),
                            Code = "auth.last_active_device_account.read",
                            Name = "Auth Last Active Device Account Read"
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auth_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_roles_code");

                    b.ToTable("auth_roles", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            Code = "platform_owner",
                            Name = "Platform Owner"
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_auth_role_permissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("auth_role_permissions", "app");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("402957af-25c0-455b-a753-1576a5ecfa91")
                        },
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("6a6f1e27-b895-423a-af08-f0a1d8e77b0d")
                        },
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("34d52b4e-d652-4d27-9f4a-6d6f706ce3c0")
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("access_token_hash");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsOfflineRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offline_restricted");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTimeOffset>("RefreshExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_access_token_hash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_refresh_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("auth_sessions", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CurrentGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_group_node_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSignInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_auth_users");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_login");

                    b.ToTable("auth_users", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_auth_user_roles");

                    b.HasIndex("RoleId");

                    b.ToTable("auth_user_roles", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.DatabaseBootstrapMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_database_bootstrap_markers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_database_bootstrap_markers_code");

                    b.ToTable("database_bootstrap_markers", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d53b52b-ab0f-4b7f-bac7-1b7f3e5e7707"),
                            Code = "initial_postgresql_foundation",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Devices.DeviceRegistration", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<Guid?>("LastKnownUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_known_user_id");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("os_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_registrations");

                    b.HasIndex("LastKnownUserId");

                    b.ToTable("device_registrations", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupAdminAssignment", b =>
                {
                    b.Property<Guid>("GroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("GroupNodeId", "UserId")
                        .HasName("pk_group_admin_assignments");

                    b.HasIndex("UserId");

                    b.ToTable("group_admin_assignments", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.HasKey("Id")
                        .HasName("pk_group_nodes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_group_nodes_code");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("group_nodes", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c15ee7fe-7c9a-4b31-8b7e-c278b59f318c"),
                            Code = "root",
                            Depth = 0,
                            IsActive = true,
                            Name = "Root"
                        },
                        new
                        {
                            Id = new Guid("d4d74008-0ed5-4e46-b0a1-91e0628079c0"),
                            Code = "branch-a",
                            Depth = 1,
                            IsActive = true,
                            Name = "Branch A",
                            ParentNodeId = new Guid("c15ee7fe-7c9a-4b31-8b7e-c278b59f318c")
                        },
                        new
                        {
                            Id = new Guid("d6370f1a-69c0-4d7f-8af5-81cf7d665e92"),
                            Code = "branch-a-sub",
                            Depth = 2,
                            IsActive = true,
                            Name = "Branch A Sub",
                            ParentNodeId = new Guid("d4d74008-0ed5-4e46-b0a1-91e0628079c0")
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthLastActiveDeviceAccount", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("LastActiveDeviceAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_last_active_device_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRolePermission", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_role_permissions_permissions_permission_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthSession", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUserRole", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_roles_role_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Devices.DeviceRegistration", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("LastKnownUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_device_registrations_auth_users_last_known_user_id");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupAdminAssignment", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", "GroupNode")
                        .WithMany("AdminAssignments")
                        .HasForeignKey("GroupNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_assignments_group_nodes_group_node_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_assignments_auth_users_user_id");

                    b.Navigation("GroupNode");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", "ParentNode")
                        .WithMany("Children")
                        .HasForeignKey("ParentNodeId")
                        .HasConstraintName("fk_group_nodes_parent_node_id");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", b =>
                {
                    b.Navigation("LastActiveDeviceAccounts");

                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", b =>
                {
                    b.Navigation("AdminAssignments");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
