// <auto-generated />
using System;
using BuildingBlocks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildingBlocks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260417074024_AddAuthFoundation")]
    partial class AddAuthFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthLastActiveDeviceAccount", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsOfflineRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offline_restricted");

                    b.Property<DateTimeOffset>("MarkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId")
                        .HasName("pk_auth_last_active_device_accounts");

                    b.HasIndex("UserId");

                    b.ToTable("auth_last_active_device_accounts", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auth_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_permissions_code");

                    b.ToTable("auth_permissions", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("402957af-25c0-455b-a753-1576a5ecfa91"),
                            Code = "auth.session.sign_in",
                            Name = "Auth Session Sign In"
                        },
                        new
                        {
                            Id = new Guid("6a6f1e27-b895-423a-af08-f0a1d8e77b0d"),
                            Code = "auth.session.refresh",
                            Name = "Auth Session Refresh"
                        },
                        new
                        {
                            Id = new Guid("34d52b4e-d652-4d27-9f4a-6d6f706ce3c0"),
                            Code = "auth.last_active_device_account.read",
                            Name = "Auth Last Active Device Account Read"
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auth_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_roles_code");

                    b.ToTable("auth_roles", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            Code = "platform_owner",
                            Name = "Platform Owner"
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_auth_role_permissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("auth_role_permissions", "app");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("402957af-25c0-455b-a753-1576a5ecfa91")
                        },
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("6a6f1e27-b895-423a-af08-f0a1d8e77b0d")
                        },
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("34d52b4e-d652-4d27-9f4a-6d6f706ce3c0")
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("access_token_hash");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsOfflineRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offline_restricted");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTimeOffset>("RefreshExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_access_token_hash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_refresh_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("auth_sessions", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CurrentGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_group_node_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSignInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_auth_users");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_login");

                    b.ToTable("auth_users", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_auth_user_roles");

                    b.HasIndex("RoleId");

                    b.ToTable("auth_user_roles", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.DatabaseBootstrapMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_database_bootstrap_markers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_database_bootstrap_markers_code");

                    b.ToTable("database_bootstrap_markers", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d53b52b-ab0f-4b7f-bac7-1b7f3e5e7707"),
                            Code = "initial_postgresql_foundation",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthLastActiveDeviceAccount", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("LastActiveDeviceAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_last_active_device_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRolePermission", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_role_permissions_permissions_permission_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthSession", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUserRole", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_roles_role_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", b =>
                {
                    b.Navigation("LastActiveDeviceAccounts");

                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
