// <auto-generated />
using System;
using BuildingBlocks.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BuildingBlocks.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260418135622_AddFraudSignalsFoundation")]
    partial class AddFraudSignalsFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Audit.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("request_path");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_records");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_records_occurred_at_utc");

                    b.HasIndex("SubjectUserId")
                        .HasDatabaseName("ix_audit_records_subject_user_id");

                    b.HasIndex("Category", "Action")
                        .HasDatabaseName("ix_audit_records_category_action");

                    b.ToTable("audit_records", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthLastActiveDeviceAccount", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsOfflineRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offline_restricted");

                    b.Property<DateTimeOffset>("MarkedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId")
                        .HasName("pk_auth_last_active_device_accounts");

                    b.HasIndex("UserId");

                    b.ToTable("auth_last_active_device_accounts", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auth_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_permissions_code");

                    b.ToTable("auth_permissions", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("402957af-25c0-455b-a753-1576a5ecfa91"),
                            Code = "auth.session.sign_in",
                            Name = "Auth Session Sign In"
                        },
                        new
                        {
                            Id = new Guid("6a6f1e27-b895-423a-af08-f0a1d8e77b0d"),
                            Code = "auth.session.refresh",
                            Name = "Auth Session Refresh"
                        },
                        new
                        {
                            Id = new Guid("34d52b4e-d652-4d27-9f4a-6d6f706ce3c0"),
                            Code = "auth.last_active_device_account.read",
                            Name = "Auth Last Active Device Account Read"
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_auth_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_roles_code");

                    b.ToTable("auth_roles", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            Code = "platform_owner",
                            Name = "Platform Owner"
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_auth_role_permissions");

                    b.HasIndex("PermissionId");

                    b.ToTable("auth_role_permissions", "app");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("402957af-25c0-455b-a753-1576a5ecfa91")
                        },
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("6a6f1e27-b895-423a-af08-f0a1d8e77b0d")
                        },
                        new
                        {
                            RoleId = new Guid("7a9170bc-6a0a-4a03-a948-0f6af0e38e78"),
                            PermissionId = new Guid("34d52b4e-d652-4d27-9f4a-6d6f706ce3c0")
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("access_token_hash");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsOfflineRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offline_restricted");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<DateTimeOffset>("RefreshExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_expires_at_utc");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_access_token_hash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_refresh_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("auth_sessions", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CurrentGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_group_node_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastSignInAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sign_in_at_utc");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login");

                    b.Property<string>("NormalizedLogin")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("normalized_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_auth_users");

                    b.HasIndex("NormalizedLogin")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_users_normalized_login");

                    b.ToTable("auth_users", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_auth_user_roles");

                    b.HasIndex("RoleId");

                    b.ToTable("auth_user_roles", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.DatabaseBootstrapMarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_database_bootstrap_markers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_database_bootstrap_markers_code");

                    b.ToTable("database_bootstrap_markers", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d53b52b-ab0f-4b7f-bac7-1b7f3e5e7707"),
                            Code = "initial_postgresql_foundation",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Devices.DeviceRegistration", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("device_name");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_trusted");

                    b.Property<Guid?>("LastKnownUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_known_user_id");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("model");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("os_version");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_registrations");

                    b.HasIndex("LastKnownUserId");

                    b.ToTable("device_registrations", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.FraudSignals.FraudSignalAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("SignalId")
                        .HasColumnType("uuid")
                        .HasColumnName("signal_id");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_fraud_signal_audit_records_incident_id");

                    b.HasIndex("SignalId")
                        .HasDatabaseName("ix_fraud_signal_audit_records_signal_id");

                    b.ToTable("fraud_signal_audit_records", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.FraudSignals.FraudSignalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptsInWindow")
                        .HasColumnType("integer")
                        .HasColumnName("attempts_in_window");

                    b.Property<string>("BusinessObjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("business_object_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("DuplicateCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_candidate_id");

                    b.Property<int>("DuplicateCandidatesInWindow")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_candidates_in_window");

                    b.Property<Guid?>("MatchedVideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_video_asset_id");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason_code");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("severity");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("signal_type");

                    b.Property<Guid?>("SourceVideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_video_asset_id");

                    b.Property<Guid>("UploadReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_receipt_id");

                    b.Property<Guid>("UploaderGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_group_node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateCandidateId")
                        .HasDatabaseName("ix_fraud_signal_records_duplicate_candidate_id");

                    b.HasIndex("UploadReceiptId")
                        .IsUnique()
                        .HasDatabaseName("ux_fraud_signal_records_upload_receipt_id");

                    b.HasIndex("UserId", "BusinessObjectKey", "ObservedAtUtc")
                        .HasDatabaseName("ix_fraud_signal_records_user_business_observed");

                    b.ToTable("fraud_signal_records", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.FraudSignals.FraudSuspicionIncidentAssignmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_admin_user_id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid>("AssignmentGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_group_node_id");

                    b.Property<string>("AssignmentReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assignment_reason");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminUserId")
                        .HasDatabaseName("ix_fraud_suspicion_incident_assignments_admin_user_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_fraud_suspicion_incident_assignments_incident_id");

                    b.HasIndex("IncidentId", "AssignedAdminUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_fraud_suspicion_incident_assignments_incident_admin");

                    b.ToTable("fraud_suspicion_incident_assignments", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.FraudSignals.FraudSuspicionIncidentDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_fraud_suspicion_incident_decisions_incident_id");

                    b.ToTable("fraud_suspicion_incident_decisions", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.FraudSignals.FraudSuspicionIncidentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessObjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("business_object_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("DuplicateCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_candidate_id");

                    b.Property<bool>("EscalatedHigher")
                        .HasColumnType("boolean")
                        .HasColumnName("escalated_higher");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason_code");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid")
                        .HasColumnName("signal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("UploadReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_receipt_id");

                    b.Property<Guid>("UploaderGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_group_node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SignalId")
                        .IsUnique()
                        .HasDatabaseName("ux_fraud_suspicion_incidents_signal_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_fraud_suspicion_incidents_status");

                    b.HasIndex("UploaderGroupNodeId")
                        .HasDatabaseName("ix_fraud_suspicion_incidents_uploader_group_node_id");

                    b.ToTable("fraud_suspicion_incidents", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupAdminAssignment", b =>
                {
                    b.Property<Guid>("GroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.HasKey("GroupNodeId", "UserId")
                        .HasName("pk_group_admin_assignments");

                    b.HasIndex("UserId");

                    b.ToTable("group_admin_assignments", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.HasKey("Id")
                        .HasName("pk_group_nodes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_group_nodes_code");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("group_nodes", "app");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c15ee7fe-7c9a-4b31-8b7e-c278b59f318c"),
                            Code = "root",
                            Depth = 0,
                            IsActive = true,
                            Name = "Root"
                        },
                        new
                        {
                            Id = new Guid("d4d74008-0ed5-4e46-b0a1-91e0628079c0"),
                            Code = "branch-a",
                            Depth = 1,
                            IsActive = true,
                            Name = "Branch A",
                            ParentNodeId = new Guid("c15ee7fe-7c9a-4b31-8b7e-c278b59f318c")
                        },
                        new
                        {
                            Id = new Guid("d6370f1a-69c0-4d7f-8af5-81cf7d665e92"),
                            Code = "branch-a-sub",
                            Depth = 2,
                            IsActive = true,
                            Name = "Branch A Sub",
                            ParentNodeId = new Guid("d4d74008-0ed5-4e46-b0a1-91e0628079c0")
                        });
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Incidents.DuplicateIncidentAssignmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedAdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_admin_user_id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid>("AssignmentGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_group_node_id");

                    b.Property<string>("AssignmentReason")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("assignment_reason");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAdminUserId")
                        .HasDatabaseName("ix_duplicate_incident_assignments_admin_user_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_duplicate_incident_assignments_incident_id");

                    b.HasIndex("IncidentId", "AssignedAdminUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_duplicate_incident_assignments_incident_admin");

                    b.ToTable("duplicate_incident_assignments", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Incidents.DuplicateIncidentAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_duplicate_incident_audit_records_incident_id");

                    b.ToTable("duplicate_incident_audit_records", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Incidents.DuplicateIncidentDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<Guid>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("notes");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_duplicate_incident_decisions_incident_id");

                    b.ToTable("duplicate_incident_decisions", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Incidents.DuplicateIncidentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DuplicateCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_candidate_id");

                    b.Property<bool>("EscalatedHigher")
                        .HasColumnType("boolean")
                        .HasColumnName("escalated_higher");

                    b.Property<string>("MatchKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("match_kind");

                    b.Property<Guid>("MatchedVideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_video_asset_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SourceVideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_video_asset_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("UploaderGroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_group_node_id");

                    b.Property<Guid>("UploaderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploader_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DuplicateCandidateId")
                        .IsUnique()
                        .HasDatabaseName("ux_duplicate_incidents_duplicate_candidate_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_duplicate_incidents_status");

                    b.HasIndex("UploaderGroupNodeId")
                        .HasDatabaseName("ix_duplicate_incidents_uploader_group_node_id");

                    b.ToTable("duplicate_incidents", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoDuplicates.VideoDuplicateAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessObjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("business_object_key");

                    b.Property<string>("ByteSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("byte_sha256");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ExternalVideoId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_video_id");

                    b.Property<Guid?>("GroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_node_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("PreUploadCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("pre_upload_check_id");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at_utc");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("UploadReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_receipt_id");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessObjectKey")
                        .HasDatabaseName("ix_video_duplicate_assets_business_object_key");

                    b.HasIndex("UploadReceiptId")
                        .IsUnique()
                        .HasDatabaseName("ux_video_duplicate_assets_upload_receipt_id");

                    b.HasIndex("ByteSha256", "SizeBytes")
                        .HasDatabaseName("ix_video_duplicate_assets_fingerprint");

                    b.ToTable("video_duplicate_assets", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoDuplicates.VideoDuplicateCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<string>("MatchKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("match_kind");

                    b.Property<Guid>("MatchedVideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_video_asset_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("SourceVideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchedVideoAssetId")
                        .HasDatabaseName("ix_video_duplicate_candidates_matched_asset_id");

                    b.HasIndex("SourceVideoAssetId")
                        .HasDatabaseName("ix_video_duplicate_candidates_source_asset_id");

                    b.HasIndex("SourceVideoAssetId", "MatchedVideoAssetId", "MatchKind")
                        .IsUnique()
                        .HasDatabaseName("ux_video_duplicate_candidates_pair_kind");

                    b.ToTable("video_duplicate_candidates", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoDuplicates.VideoDuplicateFingerprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FingerprintKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint_kind");

                    b.Property<string>("FingerprintValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("fingerprint_value");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoAssetId")
                        .HasDatabaseName("ix_video_duplicate_fingerprints_video_asset_id");

                    b.HasIndex("FingerprintKind", "FingerprintValue", "SizeBytes")
                        .HasDatabaseName("ix_video_duplicate_fingerprints_kind_value_size");

                    b.ToTable("video_duplicate_fingerprints", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoDuplicates.VideoDuplicateRegistryAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("DuplicateCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_candidate_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("VideoAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_asset_id");

                    b.HasKey("Id");

                    b.HasIndex("VideoAssetId")
                        .HasDatabaseName("ix_video_duplicate_registry_audit_records_asset_id");

                    b.ToTable("video_duplicate_registry_audit_records", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoUpload.VideoUploadPreUploadCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessObjectKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("business_object_key");

                    b.Property<string>("ByteSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("byte_sha256");

                    b.Property<bool>("CanUploadToSite")
                        .HasColumnType("boolean")
                        .HasColumnName("can_upload_to_site");

                    b.Property<DateTimeOffset>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at_utc");

                    b.Property<DateTimeOffset>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at_utc");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("decision");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("ExistingPreUploadCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("existing_pre_upload_check_id");

                    b.Property<string>("ExternalVideoId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_video_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("GroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_node_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reason_code");

                    b.Property<string>("RequiredNextSteps")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("required_next_steps");

                    b.Property<string>("SiteProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("site_provider");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckedAtUtc")
                        .HasDatabaseName("ix_video_upload_pre_upload_checks_checked_at_utc");

                    b.HasIndex("ByteSha256", "SizeBytes")
                        .HasDatabaseName("ix_video_upload_pre_upload_checks_fingerprint");

                    b.HasIndex("UserId", "BusinessObjectKey")
                        .HasDatabaseName("ix_video_upload_pre_upload_checks_user_business_object");

                    b.ToTable("video_upload_pre_upload_checks", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoUpload.VideoUploadReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisJobStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("analysis_job_status");

                    b.Property<string>("ByteSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("byte_sha256");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("ExternalVideoId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_video_id");

                    b.Property<Guid?>("GroupNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_node_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("PreUploadCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("pre_upload_check_id");

                    b.Property<string>("ReceiptStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("receipt_status");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SiteStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("site_status");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_video_upload_receipts_idempotency_key");

                    b.HasIndex("PreUploadCheckId")
                        .HasDatabaseName("ix_video_upload_receipts_pre_upload_check_id");

                    b.HasIndex("ByteSha256", "SizeBytes")
                        .HasDatabaseName("ix_video_upload_receipts_fingerprint");

                    b.ToTable("video_upload_receipts", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoUpload.VideoUploadReceiptAnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("command_name");

                    b.Property<DateTimeOffset>("EnqueuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at_utc");

                    b.Property<Guid>("PreUploadCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("pre_upload_check_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<Guid>("UploadReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_receipt_id");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_video_upload_receipt_analysis_jobs_status");

                    b.HasIndex("UploadReceiptId")
                        .HasDatabaseName("ix_video_upload_receipt_analysis_jobs_upload_receipt_id");

                    b.ToTable("video_upload_receipt_analysis_jobs", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.VideoUpload.VideoUploadReceiptAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("category");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("UploadReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("upload_receipt_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_video_upload_receipt_audit_records_correlation_id");

                    b.HasIndex("UploadReceiptId")
                        .HasDatabaseName("ix_video_upload_receipt_audit_records_upload_receipt_id");

                    b.ToTable("video_upload_receipt_audit_records", "app");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthLastActiveDeviceAccount", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("LastActiveDeviceAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_last_active_device_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRolePermission", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_role_permissions_permissions_permission_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthSession", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUserRole", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_roles_role_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Devices.DeviceRegistration", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("LastKnownUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_device_registrations_auth_users_last_known_user_id");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupAdminAssignment", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", "GroupNode")
                        .WithMany("AdminAssignments")
                        .HasForeignKey("GroupNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_assignments_group_nodes_group_node_id");

                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_assignments_auth_users_user_id");

                    b.Navigation("GroupNode");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", b =>
                {
                    b.HasOne("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", "ParentNode")
                        .WithMany("Children")
                        .HasForeignKey("ParentNodeId")
                        .HasConstraintName("fk_group_nodes_parent_node_id");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthPermission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.Auth.AuthUser", b =>
                {
                    b.Navigation("LastActiveDeviceAccounts");

                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("BuildingBlocks.Infrastructure.Persistence.Entities.GroupTree.GroupNode", b =>
                {
                    b.Navigation("AdminAssignments");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
